#!/bin/bash

# This is a bash script that toggles otter-launcher with foot terminal.
# Modify foot --app-id to others, for example alacritty --class, if you use other emulators.
# When run, otter-launcher will be launched if not already running, be focused if running but not being focused, and be closed when already running and focused.
export TERM=ghostty

if [ -z $(hyprctl clients | grep "class:com.free.otter-launcher") ]; then
  hyprctl dispatch exec 'ghostty --class="com.free.otter-launcher" --title="otter-launcher" -e otter-launcher'
else
  echo application_already_Running
  if [ -z $(hyprctl activewindow | grep "class:com.free.otter-launcher") ]; then
    hyprctl dispatch 'focuswindow class:com.free.otter-launcher'
  else
    hyprctl dispatch killactive none
  fi
fi
