return {}
-- return {
--   "ravitemer/mcphub.nvim",
--   dependencies = { "nvim-lua/plenary.nvim" },
--   build = "npm install -g mcp-hub@latest",
--   config = function()
--     require("mcphub").setup({
--       port = 3000,
--       config = vim.fn.expand("~/.config/nvim/mcpservers.json"),
--       log = { level = vim.log.levels.WARN },
--       on_ready = function()
--         vim.notify("MCP Hub запущен!")
--       end,
--     })
--   end,
-- }
